name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *" # Atur jadwal sesuai kebutuhan Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Make changes
        run: |
          echo "Auto Commit" >> automated-file.txt
      - name: Commit files
        run: |
          git add .
          git commit -m "Automated commit message"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
